server:
 port: 8081
 servlet.context-path: /springbootTest
 #name1: 小芳
#person:
 #name: 小胖
 #age: 22
spring:
 profiles:
 active: a
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot
  username: user
  password: l123456

 jpa:
  hibernate:
  ddl-auto: update
  show-sql: true